name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install buildozer cython
        sudo apt-get update
        sudo apt-get install -y git unzip openjdk-11-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
        
    - name: Accept Android licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/android-sdk-license
        echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > ~/.android/android-sdk-license
        yes | /usr/lib/jvm/temurin-11-jdk-amd64/bin/sdkmanager --licenses || true
        
    - name: Build APK with Buildozer
      run: |
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: professional-downloader-apk
        path: bin/*.apk
